title: Mohammed Salah
logo: facefocused-modified-resized.png
description: <br> Welcome To my Portfolio, I am Mohammed Salah. Nice to meet you!
show_downloads: true
favicon: logo.ico
theme: jekyll-theme-minimal
